otm_amber_heard_transcript = r"""Brooke Gladstone: "Thus ends the #MeToo Movement," tweeted conservative mischief-maker, Ann Coulter. This Wednesday afternoon in Fairfax County circuit court in Virginia, a jury awarded Johnny Depp $15 million in damages in his libel suit against his ex-wife Amber Heard and gave her 2 million in her countersuit against him. All this over a December 2018 op-ed she wrote in the Washington Post describing herself as "a public figure, representing domestic abuse." Depp's lawyers said that he was defamed by the article, even though it never mentioned his name.
This case argued over six weeks before a seven-person, jury, and judge and a noisy expanding online audience drove much of the internet crazy with guilty pleasure, except in precincts where the idea that women were regularly abused and had the right to say so was beyond the pale. In those places the pleasure was guiltless enhanced by the collective hurling of feces at Amber Heard, who did not deserve it based on the evidence gathered meticulously in a British libel case, also focused on Depp's spousal abuse.
The only quarter of the media that seemed reluctant to engage, at least in the facts of the case was the progressive press or the liberal media. There you could find a coverage of the brouhaha, but not the underlying reality. This bothered journalist Michael Hobbes host of the podcast Maintenance Phase, who observed that the usually reliable outlets tended to steer around the facts and in, so doing sold an already victimized woman down the river, at least that's how I see his argument. I'll find out if I'm right, Michael, welcome back to On the Media.
Michael Hobbes: Thanks for having me and apologies for the emails that will fill up your inbox after you do this.
Brooke Gladstone: It wouldn't be the first time. When we look at the media coverage of the Depp v. Heard trial, we see two things. You've observed people on the right, saying, "Amber's a liar," and people on the left skirting around the topic saying, "It's complicated." You saw a reluctance by liberal journalists to actually assess the facts of the case, a reluctance to look into something so messy, and to begin you felt that way yourself.
Michael Hobbes: I think I had the trajectory that a lot of people did where I had seen this pop up over the last couple of years. There was a case in the UK, of course, and every once in a while, you'd see something like Amber Heard is a psychopath or something trending on Twitter. Then I'd look at it and be like, "Ooh, man, it's dark in there. Something's going on," but I didn't really investigate.
Then when this trial started in the US, I think a lot of us don't want to admit how much we're informed by this inchoate sense of what people are saying. You hear on the wind that like, "This new movie is good or this new movie sucks or something," but you can't really identify exactly where you heard that.
Brooke Gladstone: I think that's called the sleeper effect.
Michael Hobbes: I like to think of myself as smarter than it. I don't think that I actually am. In the early days of this case, there were a couple of clips going around of Amber Heard that sounded quite bad and people were saying that she was really manipulative and lying and it seemed like a really clear-cut case of a woman going after a man. There was a part of me that was like, "Well, I'm just going to wait on this one. I'm going to wait till there's a verdict. I'm going to wait until there's more information available."
I don't know if that's what most of the rest of progressive [unintelligible 00:03:49] did, but it feels like that's what people did. The major establishment, progressive outlets have barely covered this trial. When they've gotten interested more recently, it's mostly been as an online bullying story as a people on the internet are being horrible to Amber Heard, which is undoubtedly true, but then I think they stopped short at saying, they're being unjustly mean to Amber Heard and Amber Heard is a victim and focusing on the injustice. It's more like, "Well, it's a very complicated case, but regardless of the fact, nobody deserves the treatment that she's getting."
Brooke Gladstone: Regardless of the facts is a phrase that you've seen or words to that effect that have really gotten up your nose.
Michael Hobbes: Yes, I think journalists should never be putting facts aside as a profession and I actually, I got radicalized on this when I went on YouTube and I have shown no interest in this trial, I have not clicked on things. I'm not Googling anything. I was planning to ignore it. Then on YouTube, I start getting fed these videos that are like Amber Heard's body language shows that she's a sociopath, huge red flag. This is what we got with Carole Baskin. This is what we got with Amanda Knox. This is what we got with Megan Markle.
It's like, when you don't have evidence against a woman, you start using body language, and these like little clips taken out of context. Then I started to get slightly more interested and I started looking around and I finally went to the UK case. This almost the exact trial that we're having now in Virginia has already been decided in the UK two years ago.
Brooke Gladstone: It was also a libel case that Johnny Depp brought and the big difference is that it's much harder for a publication to win a libel case in the UK than it is here. There's a different standard.
Michael Hobbes: Yes. It should have been very easy for Johnny Depp to win that case and he didn't win. That decision is available online and it's 126 pages long. It's actually very clearly written. It's very cogent. It basically goes through 14 incidents of violence that Amber Heard alleges happened in the relationship.
It very clearly lays out, okay, here's the evidence for Johnny Depp's account. Here's the evidence for Amber Heard's account. It says of those one is thrown out on a technicality. Another one, the judge isn't convinced, but on 12 of those incidents, the evidence indicates that Johnny Depp was violent toward Amber Heard.
Brooke Gladstone: Based on what?
Michael Hobbes: Based on-- It's actually quite remarkable once you get into it. This is really what radicalized me is that very few domestic abuse victims have as much evidence as Amber heard. She has contemporaneous texts from very early in the relationship two years before they even got married, she was texting her mom and saying, "I think I'm in love with someone who's abusive." She was telling her friends, "I'm afraid of this guy getting violent with me."
Her acting coach says sessions are supposed to be an hour-long, but we had to schedule them for two or three hours because she was so distraught from what Johnny Depp was doing to her. We have witnesses who say they covered up her bruises with makeup. We have photos. We have texts from Johnny Depp himself kind of, sort of not admitting to the abuse, but admitting to drinking to the point of blackout, which is the heart of her accusation of abuse that most of the incidents of violence took place when he was drinking so bad that he couldn't remember what happened the next day.
We have his staff texting her the next day and saying, "When I told him he hit you, he cried." You look at all the evidence and I don't know of other public domestic abuse cases where there's been this much evidence. I was comfortable believing Christine Blasey Ford. I was comfortable believing the accusers of Weinstein and Cosby, and they had much less evidence than this.
Brooke Gladstone: If the mainstream media had wanted to engage, they could have. This information was available and collated for their convenience if they were willing to read through more than 100 pages. That said, what is the consequence of the progressive media, even the mainstream media's reluctance to engage with that evidence?
Michael Hobbes: I want to offer some amnesty on this because I think a lot of people did this out of a place of generosity thinking that, "Hey, this is ugly in there. I don't really want to engage. I might be retraumatizing this person by adding more attention to it, but the effect of that ultimately was that we had three or four weeks when almost nobody on the liberal media side was covering this case. The right wing media was having an absolute field day with this.
We had rumors just straightforward misinformation from the opening arguments, we were getting misinformation about Amber Heard's case. We were getting all of this, especially on TikTok, these video clips where people would take Amber Heard's testimony out of context and they would make it seem like she was lying. They would juxtapose clips to make it seem like she was being deceitful. When did this happen? When in the day did this happen? First she said this, and then she said that.
It's quite easy to do this and make somebody look like a liar on the stand. It allowed bad faith actors to plant a lot of seeds that then you have to go and pull up like weeds. It's much harder to deal with this stuff once it's been entrenched, then it is if there's two narratives going on at the same time. For weeks, the only narrative was Amber Heard is a manipulative psychopath and Johnny Depp is the victim of abuse. That was the only thing that most Americans were hearing.
Brooke Gladstone: You mentioned TikTok, a lot of this, as many of these kinds of narratives do started on a whole range of social media, a popular podcast where the hosts were congratulating themselves on not weighing in. Maybe that's the least of it. What were some of the complete misinformation? The things that were absurd.
Michael Hobbes: One of the early ones was that in Amber Heard's opening statement, she said that
dating Johnny Depp was like the warm sun shines upon you and then the sun burns out, and then it's very cold, or something along those lines. Which, it turns out, is a line from The Talented Mr. Ripley. The idea was that she had plagiarized this line from The Talented Mr. Ripley. First of all, people do that with movies all the time.
It's fairly normal to quote movie lines when you're talking about your relationship. Second of all, Amber Heard didn't give an opening statement. There's no such thing as an opening statement where Amber Heard said this quote. The entire premise of this plagiarism is just completely made up, there's no evidence that she ever said this. This nothing-burger of an accusation bounced around. Did you hear the one about the make-up palette?
Brooke Gladstone: No.
Michael Hobbes: One of the arguments against Amber Heard is that if Johnny Depp was so violent, why do so many people report seeing her without bruises? This is what I consider to be a very bad faith accusation because bruises are fairly easy to cover up with make-up, especially if they're relatively minor bruises, and that's what she says they are. In opening arguments, her lawyer held up a make-up palette as a kind of example, like a visual aid, to say the reason why people didn't see her with bruises is this, it's a make-up palette.
You can use concealer and you can cover up your bruises. Then the flying internet monkeys that have been swarming around this case for weeks now, they zoomed in on the image. They found the brand that Amber Heard's lawyer was holding up and they started tagging this make-up brand and saying, "Her lawyer says she used your product to cover up her bruises." This is really ugly, the actual make-up brand then put out a debunking tweet saying, "We only started making this make-up palette in 2017 so Amber Heard is lying.
There's no way Amber Heard could have used it in her relationship to Johnny Depp, between 2012 and 2016." Of course, that leaves out the fact that in the opening arguments, they didn't say that she was using this specific brand. They were using it as an example. This is make-up, she used make-up. That's it. Of course, by the time you try to debunk these things, it's gone around the world three times and it gets cast as just like, "Oh, she's proven to be lying on the stand," when the entire premise of that makes no sense.
Brooke Gladstone: Who are the people who are so intent on depicting Amber Heard as a psychopath?
Michael Hobbes: I think there's a very large contingent on the right, that wants any excuse to say that #MeToo has been a scam all along. They have been searching for a case where a woman uses the #MeToo Movement as a horse that they can ride into infamy. A woman who makes up a claim using the Me Too movement, they've been desperate for this. Johnny Depp has also explicitly endorsed this view.
In the legal filings, he says that this is a hoax that Amber Heard is using to advance her career. This is the meta-myth of the backlash against #MeToo, that women can use this to advance their careers.
Brooke Gladstone: That works out really well.
Michael Hobbes: That's the thing. I was trying to think of a single example where this is true, like Anita Hill, or Christine Blasey Ford, it hasn't really worked out well for people. It doesn't make any sense on its face and it super-duper doesn't make sense in this case. The narrative that she's a gold digger is belied by the fact that she didn't get terribly much money in their divorce. She only got $7 million.
She was entitled to somewhere around 30 million. She didn't have to allege abuse to get a huge settlement in the divorce because there was no prenuptial agreement, so she could have just, "Hi, I want a divorce," and she would have gotten half of his earnings. Those are the bad faith people that I think have latched on to this. I also think there's, disappointingly, a very large contingent of people across the ideological spectrum who are just willing to believe that a woman made up a claim of abuse to advance her own career.
This is a meta myth that we've gotten a million times. It's something that appears in a lot of stories that have caught on, it's something that I think a lot of people believe somewhere in their brain, and they turn off their critical faculties when a story meets these criteria. What we've had is this phenomenon that people have been colloquially calling True Crime Brain. There's a lot of these small discrepancies in Amber Heard's account. The biggest one is, she says that she donated her divorce settlement to charity.
Brooke Gladstone: Half to the ACLU, and half to-- What was the other half?
Michael Hobbes: Children's Hospital, LA.
Brooke Gladstone: Right.
Michael Hobbes: This seems like her main claim that she's not a gold digger, "I gave away all the money," she said under oath that she donated all this money. Then, in the course of this trial, it comes out that the ACLU, which should have received $3,500,000, has only received about $1,700,000. Some of it was in Johnny Depp's name and some of it was in Elon Musk's name. The whole thing just starts to seem like she's been running this scam for the entire time.
This goes around and this is oftentimes cast as one of her proven lies on the stand. She said that she donated the money, under oath, and now it comes out she hasn't donated the money. Looks bad. Of course, once you show any natural human interest in what actually happened, the ACLU has testified in this case that they had always planned, with Amber Heard, for her to give it away over 10 years. This is fairly normal for these large-scale donations.
She paid the first year and during the second year, she started getting sued by Johnny Depp, and she now says she spent $6,000,000 defending herself from these lawsuits. According to the ACLU, she had been completely transparent with them and she said, "Hey, all my money is tied up in this lawsuit right now, I can't pay the second year. I still intend to pay the rest, can we put it on hold for a year?" The ACLU said, "Sure, that's fine, these things happen."
The lie that she's been caught in, the proven lie that proves that she's a sociopath, whatever, is basically that she should have said the word pledged. "I pledged my divorce settlement, rather than donated." Sure, fine, I think it's fair to say, okay, she could've been more precise with that language, especially if you're under oath, fine. It doesn't strike me as evidence of the kind of sociopathic gone-girl calculation that would be required to pull off a years-long scam to fake the abuse of your husband and scam him out of millions. It's a fairly small thing.
Brooke Gladstone: Right. If this were true, this would indicate that she's a manipulator. I think the sociopathy argument was being made through a massive misunderstanding of a story involving poop.
Michael Hobbes: Oh, gosh. Ugh. Just the sigh overtakes me when I hear about having to talk about the poop story.
Brooke Gladstone: [laughs] Well, I only bring it up because it seems to have taken up a lot of air space in the media ecosphere.
Michael Hobbes: Oh, my God. Yes, it's just the perfect metaphor for the sewer pipe of information that the internet has become around this trial. The theory is that Amber Heard, as a form of revenge on Johnny Depp, because she's an abusive sociopath, she pooped on his bed after they had a fight. This is something that goes around, you can discount every single thing that she says because, look, she pooped on the bed, it's confirmed.
Then, again, the minute you show any actual interest in this, what actually happened was-- They had, the previous night, they had gotten in a really big fight. He had disappeared for days, as he often did when he was drinking, according to Amber Heard, and he had shown up late and drunk to her 30th birthday party. Almost all of the abuse took place when he was drinking and blacked out, so she was really upset by this.
They had talked and he had promised to get sober, then he shows up at her birthday party and he's drunk. They get in a big fight after that and he storms off to one of their other houses. Then he gets a text the next day, from his manager, who had gotten a text from the house cleaner saying, "I came to the house and there's this big piece of poop on the bed." The story, once you break it down from her perspective, it doesn't make a lot of sense as a revenge plot.
First of all, he was not sleeping there. He had stormed off. Actually, it will be another month before they see each other face to face. This often happened after their fights, there will be weeks-long periods where they're not speaking to each other. He had stormed off to sleep in one of their other, like, 55 houses that these people own, then she pooped in the bed as a form of revenge on her husband, who wasn't sleeping there, and made no attempt to tell him.
She didn't text it to him like, "Hey buddy, this is what I think of you," there was no attempt to do anything. She had essentially just left it for the cleaning person to clean up. That's the most basic expectation of what would happen in a situation like that. If it's a revenge plot, where she just did this and then didn't tell him, it's totally baffling. Then we also have text messages from her, about a year before, about their dog who had some sort of allergy, where he couldn't control his little poops, and he had pooped on the bed before. Amber Heard, in that case, had actually cleaned it up, so that the cleaner wouldn't have to do it because it's insulting to make the cleaner clean up their dog's poo. What we have here is a perfectly plausible story, that their dog who pooped on the bed, pooped on the bed again. We also have a
a story about a 30-year-old woman pooping in her own bed and then not telling her husband about it even though she did it as revenge on her husband.
It's like one case is plausible and then the other case is totally deranged. Then what you've gotten is this weird circular logic where it's like, she have to be a total weirdo to do something like that. Then people on the internet are like, "Well, she is a weirdo." It's like, "What's the evidence that she's a weirdo?" "Oh, she pooped on the bed." It's like, "Wait a minute. That's what we're talking about. You can't just assert that."
Brooke Gladstone: Researching this interview, there was some clearly unfounded assertion on some site that this was clearly human poo.
Michael Hobbes: Oh yes. This is another one that the house cleaner said in her deposition that to her, she was like, this has to be human poo. There's no way this is dog poo. I don't know. Is the cleaning person a forensic analysis? To me it's like, everything is likelihood in these cases. You can't say 100% certainty that one thing happened or another. Again, what is more likely a 30 year old woman who has no history of behavior like this pooped on a bed to no benefit to herself whatsoever, or a cleaning person was mistaken about the type of poop that it was.
Brooke Gladstone: If we take a step back and look at their stories overall, the ones that each of them maintained Johnny Depp believes that this plot against him by Amber Heard began, I don't know, many years ago.
Michael Hobbes: If his account of events is true, essentially as soon as they moved in together, she began fabricating incidents of violence against him. That is the only way for his narrative of events to make sense. His accounting of events is essentially a conspiracy theory in which she has faked photographs. She has doctored the metadata of evidence. She has painted on bruises. He accused her of cutting herself to make it look like it was broken glass after a fight that they had.
The amount of premeditation that would go into this again, her acting coach testified for her. Her friends testified for her. She has somehow convinced nearly a dozen people to testify under oath in numerous cases on her behalf. Somehow she has left no trace of this. No email saying, remember a lie under oath for me tomorrow. Nothing. I don't know about you.
I cannot organize a book club meeting without 12 emails, coordination and who is where, and who's going to bring this. The idea that she has done this massive conspiracy, which also aligns with quite a bit of his own evidence of the timeline without leaving any trace, it's just really implausible.
Brooke Gladstone: She'd have to be a mastermind. The first incident was in March of 2013. That was two years before they were even married. Was that part of the plot?
Michael Hobbes: It would have to be because she texts her mom and she texts friends and she tells her acting coach. If she's fabricating all of this, she would've had to start fabricating this two years before they were married and three and a half years before they were getting divorced all in an effort to get more money out of him in the divorce settlement that she was already entitled to. She also, as part of the divorce settlement signed an NDA and withdrew the abuse allegations that she had made when she filed the restraining order.
Then she didn't speak about it. She's fabricated all of this abuse. She makes the abuse claims. She then agrees with him to withdraw the abuse claims when they settled the divorce. Then she doesn't say anything for a year and a half. Again, strange behavior for a criminal mastermind who wants to use this to get ahead in Hollywood.
Brooke Gladstone: To Depp's defense, you've made this observation yourself. He might sincerely believe given that he is prone to blackouts, he may sincerely believe in what he's alleging.
Michael Hobbes: It feels like every time we have one of these, everyone forgets everything we've learned before about abuse dynamics. I think it's really important to actually hear the narrative that Amber Heard is telling because it's an extremely familiar story of abuse dynamics. When she first met Johnny Depp, he was sober. Early in their relationship around March of 2013, he fell off the wagon and once he started drinking again, he would disappear for days.
He would return as a different person. He would accuse her of hoeing herself out in Hollywood. He would speak really negatively about other actresses. He criticized her for wearing a low-cut dress. She says she stopped telling him about auditions because he would start grilling her about whether or not there were love scenes with male actors. What they really fell into was this cycle where he would get drunk or use drugs to the point of blacking out.
Then he would hit her. Then the next day he would deny it. He would deny that he had a drug problem and he would deny that he ever hit her. He would deny that he was ever abusive. There's this deep denial and I think shame associated with being the addict who hits a woman like this is a very stigmatized, I think, rightly category in society. I don't say this to defend the behavior at all, but this is a very familiar abuse pattern especially when drugs and alcohol are involved.
What she describes is by late in the relationship, she's essentially the only person who is treating his drug use and his violent outbursts as a problem because of course, we have to reckon with the fact that this guy's a movie star. He's extremely wealthy. He has people, handlers around him. He has full-time doctors. He has lawyers and Heard talks about people prescribing him things to get him through shoots because the studios need him to finish the shoot.
Then he'll get into detox after the shoot is done. There's this whole machine around him to make sure that he never has to reckon with what he did last night. Nobody ever reminds him, "Oh, you trash that hotel room." He just has this bottomless checkbook and these people that will make these problems go away. When you listen to his testimony in contrast to hers, he doesn't really list very many incidents of abuse. He says that she was irritating. He says that she was abusive, but he doesn't say on this date, these text messages indicate that.
There's nothing specific in his account, but he does describe her as nagging him. Oftentimes abusers, especially people who are in denial about the fact that they're abusive will remember when their victim hits them. They'll remember when their victim was nagging at them. There's this infamous clip that went around before the trial where they are talking and he's accusing her of essentially being abusive. Amber Heard taunts him. She's like, "Oh, go ahead, go ahead. Tell the media. Tell them I, Johnny Depp, I'm a victim of abuse."
It sounds terrible. This is one of the clips that I heard. I was like, "Oh man. This is really bad. She sounds awful." If you listen to it out of context, it really does seem like an act of abuse. There's a real case to be made that somebody who talks to their partner like that is abusive. If you're viewing it out of context, but if you view the entire transcript and if you view it in the context of actually believing her, if you're in a relationship where somebody is hitting you, using drugs constantly, and then denying everything the next day and accusing you of being the abusive one.
She talks on the stand of this learned helplessness that takes over where she is like, "You know what, forget it. Tell the media." You're basically in the middle of being gaslit by somebody who's been in this abuse and apology and denial cycle for years. He is accusing you of abuse. If you view it from the perspective of she's lying, then it looks really bad. If you view it from the perspective of actually believing her entire narrative of the relationship, it starts to make a lot of sense that she would do that. Do you find that convincing?
Brooke Gladstone: Yes, I absolutely do. It's like, you are the abused one. If you've been going through this for years and years, this is just such an old story.
Michael Hobbes: I've heard from people that researched this. This is a relatively common thing that abusers do that once the victim starts fighting back. They will often use, "Oh, she gave me a bloody nose," as a first strike. I think people know that whoever's account of events you hear first is oftentimes dispositive. If you're in an abusive relationship and you know on some level that you're an abuser to then go to your group of friends and be like, "You know Sally gave me a bloody nose the other day."
That's a way to get ahead of it. I don't know that that's exactly what's happening here, but this is a fairly familiar trope in actual abuse situations. This is what Amber Heard is claiming. I also think what's really interesting is if you watch her actual testimony, she's very open about the fact that by the last year of the relationship, she was fighting back. She was starting arguments. She escalated things. She was shouting. They were calling each other ugly names. She's always been very open about the fact that she did not behave great in this relationship. She didn't ask for this. He is suing her and she was not someone who wanted to bring this out into the public eye. She's always been really transparent about the fact that her actions weren't always great. People don't react to abuse in pro-social ways. This is also something which
is very familiar from abuse cases.
Most of his accusations against her, if you listen to his account of events, it's like, "Okay, she was annoying. She could nag you. She was condescending about your drug use." She would kinda roll her eyes if you're like, "Oh, I'm getting get sober this time." Okay, I don't know that's not great behavior, but she has 10 documented incidents of you beating her up and giving her black eyes and slamming her to walls and tearing out chunks of her hair, and at least two sexual assaults.
It's like, I don't know why we're talking about this. I don't know why we're talking about like, well maybe she hit him once. She's on tape saying maybe she hit him. Okay, I don't know in a vacuum, that's not great behavior, but also if you look at this relationship as a whole and what the evidence indicates, she has a very strong case for believing her.
Even the fact that he is doing this is in some way, evidence of her account. Part of her account is that he had these paranoid conspiracy theories that he was accusing her of all the time. Now he's suing her for destroying his career. Right, she wrote half a sentence about him in the Washington Post in 2018.
Brooke Gladstone: He's ignoring the libel suit that he lost in England prior to that.
Michael Hobbes: There's been numerous magazine articles before this, about Johnny Depp's fading star. He had, I think it was six bombs in a row. He was in this Alice in Wonderland sequel that nobody's ever heard of. He was in The Lone Ranger, which was such a flop that it's a legend at this point.
He's also just getting older and Hollywood thrives on youth. There's a million reasons why his star was dimming in Hollywood and also they had a Disney executive testify at the trial who was talking about why they removed him from the Pirates of the Caribbean films. She was like, no one even saw the op-ed. We didn't even know that was happening and there's some evidence that they actually made the decision before it came out.
Brooke Gladstone: This is all about the op-ed.
Michael Hobbes: Yes, this whole trial, he is suing her for defamation, for an op-ed in which she only referred to him in a half a sentence. She didn't say anything that wasn't factually true. Her sentence was, "I became a public figure representing the issue of domestic abuse," which is factually true. She did become a figure representing that. She didn't say anything about him.
Brooke Gladstone: Obviously the assumption is very clearly there that it's about him but when he was suing her in London, that was about a prior defamatory statement in his view.
Michael Hobbes: Yes. He was suing the newspaper, The Sun for printing an article that called him a wife-beater. Then by calling Amber heard to testify and present all this evidence, they were able to prove under the statutory rules in the UK, that he was in fact, a wife-beater, the claim was substantially true. Therefore it's okay to print it. It's not defamatory if it's true.
Brooke Gladstone: He lost his case against The Sun and then he brings a case of defamation here and he doesn't Sue the Washington Post.
Michael Hobbes: Right. Exactly, which I think is telling. He also sues her for, very significantly more than she is worth. He's suing her for $50 million. In the last year of their marriage, she earned $260,000. This is not a realistic claim and I believe she spent a huge percentage of her net worth on the legal defense.
Brooke Gladstone: Circling back to the beginning, you were saying that you observed among much of the progressive media, a reluctance to dig into the facts of these charges and counter-charges, partly because of a fastidious desire, not to be walking through the muck. Also, get from me site and this is too hard but do you have any examples of media actually doing that, of this reluctance?
Michael Hobbes: I don't want to name names because I think that most people were reluctant for good reasons or for human and understandable reasons, but I think that it's almost like what we see with politics where there's, this need to give both sides, their due, even when they don't deserve it. Even when it's very clear that one actor is being worse than the other, it's like, well, these people say, and those people say.
Brooke Gladstone: Fairness bias.
Michael Hobbes: Exactly the fairness bias. This is one of the main themes of the show, right? We see that applied to many other things. I think that there's this reluctance on the part of journalists to be seen as taking sides on things. Even when I actually think that one of the roles of journalism is to just, "Hey, I have more time than you. I'm going to read all the documents in this case and I'm going to tell you my conclusions."
Brooke Gladstone: Part of our reason for doing the interview is derived from your observation. We've had it too, that there was a disinclination to dig into this stuff progressive and even just mainstream media, leaving the field wide open for far-right media and men's rights groups and gamer Gators and all of those types but you don't want to name any names.
Michael Hobbes: There's podcasts that I enjoy who I think dropped the ball on this, but I also, I don't know, they're doing their best. There was also a palpable sense that this is something frivolous, that these are two wealthy people, two attractive movie stars, embroiled in some personal civil suit and I think that there's this idea that it's too frivolous to get down into the muck of. Right, and I think refusing to provide a counter-narrative allowed right-wing people to have this one.
I also think that we live in a world where people form their opinions on things like gender and domestic violence and the relations between men and women on the basis of frivolous things. Right, you could say that some skirmish between two figure skaters in 1994, ultimately it's not that big of a deal, right? It's just two ladies fighting about stuff, but you look back and America learned a lot of things or learned the wrong things about women and about the way that men abuse women from that case.
Brooke Gladstone: For people who weren't born, then that was the Tanya Harding story. I think it's really interesting that you bring up Tanya Harding because a lot of the kinds of media that have been doing a penance by going back, correcting the record, retelling, and contextualizing the stories of women that were botched the first time around. I'm talking about Monica Lewinsky, Britney Spears, Anna Nicole Smith, Tanya Harding, that responsible media aren't engaging in the same way with Amber Heard yet. I'm just wondering why we don't seem to have learned our lesson yet.
Michael Hobbes: One of the hardest things has been watching us make exactly the same mistakes with this one that we made with Anita Hill and Tanya Harding and Anna Nicole Smith. To some extent Amy Fisher and [unintelligible 00:37:15], we've done this so many times and we see the same weaponization of these tropes about womanhood that are applied to whatever woman will do and whatever facts will do.
We're just going to run the same playbook again and again. I think that's why I've gotten so obsessed with it is because we all just watched Framing Britney, this documentary about how terrible Britney Spears was treated by the media in 2007. Then it's like, you look at what we're doing to Amber Heard and it's like, sorry, was anyone there? Did anyone pay attention to these structural elements of those stories?
The issue with Britney Spears in 2007 wasn't just that like we were really mean to Britney Spears. This is the way that we treat women in the media and people learn how to treat women from these narratives. A lot of people are taking away from this story. She's not a real abuse victim if she doesn't have big old scars and she's not a real abuse victim if she wrote him love letters.
She's not a real abuse victim, if there's no medical records. The Johnny Depp supporters keep saying that they're standing up for male victims for doing this and that male victims have been overlooked in #MeToo Movement and male victims face real challenges in coming forward. I think that's to some extent true.
I've never heard anyone deny the fact that they're male victims of domestic abuse, but the idea that we would be smearing somebody like this for not having severe enough injuries and blaming them for faking, painting, bruises on, and not coming forward earlier, it's like, what was she wearing type stuff. That doesn't help any victims, domestic abuse victims and domestic abusers, frankly, are watching this and going, "Well, this is how it works when people come forward."
It's the story that the phrase believe women was invented for, right? That instead of starting from this assumption, that society has a real problem with women making up fake claims of abuse. There's vanishingly few of these, there's even fewer against powerful men, but we still have this presumption in our heads that this happens rather than starting from just maybe she is telling the truth and trying to slot the evidence into that frame. What she's describing is something we've seen a million times before, right? We've got a powerful man who's entitled. He's surrounded by enablers. Johnny Depp has a very long history, established history of violence of outbursts. I found a 2000 Esquire article where two different directors talked about him blowing up on film sets. He's currently being sued by a crew member on another movie for allegedly punching him and then it comes to Amber Heard
saying, "Hey, I am saying that this guy did the thing to me that he's done to many other people in public and he has a very well documented history of doing."
It was like, "Ah, she's lying. I don't know about that. This guy. The guy who blows up and trashes hotel rooms. This guy? I don't know." People are treating it like it's some sort of exotic fairy tale as opposed to a story we've seen so many times.
[music]
Brooke Gladstone: Michael, thank you very much.
Michael Hobbes: Thanks for letting me get my impassioned speech just there. Sorry.
[laughter]
Michael Hobbes: I was trying to end strong, Brooke. [laughs]
Brooke Gladstone: It was great. You left strong.
Michael Hobbes: Thank you.
Brooke Gladstone: Michael Hobbes is the journalist, essayist, and host of the podcast, Maintenance Phase.
[music]
Brooke Gladstone: Thanks for listening to this week's podcast. Coming up on the big show on Friday, which posts around dinnertime, we'll be looking ahead to the hearings on the January 6th insurrection or riot or whatever you want to call that day when things were looking really bad for democracy. I'm Brooke Gladstone."""